name: Periodic Health Check

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]
# schedule:
#   - cron: '0 */3 * * *' 

jobs:
    Health_Check:
        runs-on: ubuntu-20.04
        steps:
            - name: Check app health
              uses: jtalk/url-health-check-action@f3f7bd79e4a64218eea7caad72796a1443896aeb 
              with:
                url: https://pokedex-cz3m.onrender.com/health
            - if: success()
              name: Notify Success
              uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
              with:
                severity: info
                details: https://pokedex-cz3m.onrender.com/ is up and running
                text: Pokedex is healthy
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - if: failure()
              uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
              with:
                severity: error
                details: https://pokedex-cz3m.onrender.com/ is down
                text: Pokedex is down
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

