name: deployment_pipeline

on:
    push:
        branches:
            - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
    deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
             - uses: actions/checkout@v3
             - uses: actions/setup-node@v3
               with:
                node-version: '16'
             - name: installing dependencies
               run: npm install
             - name: Linting Check
               run: npm run eslint
             - name: Build
               run: npm run build
             - name: Test
               run: npm test
             - name: e2e tests
               uses: cypress-io/github-action@v5
               with:
                 command: npm run test:e2e
                 start: npm run start-prod
                 wait-on: http://localhost:5000
             - if: ${{ github.event_name == 'push' }}
               name: deploy to render
               run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
             - name: Deploy Success
               uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
               if: success() && ${{ github.event_name == 'push' }}
               with:
                 severity: info
                 details: to https://pokedex-cz3m.onrender.com/
                 text: A new version of Pokedex is deployed!
                 webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
             - name: Build Failure
               uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
               if: failure()
               with:
                 severity: error
                 text: Build Failure
                 details: commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} is broken
                 webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    tag_release:
      needs: [deployment_pipeline]
      if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
